"use client";

import { useState } from "react";
import { createNutritionProfileDraft, nutritionProfileFromDraft, updateNutritionProfileDraft } from "@/lib/nutritionProfileDraft";
import type { NutritionProfile } from "@/lib/types";

const blank: NutritionProfile = { gender: "male", age: 25, heightCm: 175, weightKg: 70, activityLevel: "moderate", goal: "maintain" };
export function NutritionProfileForm({ profile, onSave }: { profile: NutritionProfile | null; onSave: (profile: NutritionProfile) => void }) {
  const [value, setValue] = useState(() => createNutritionProfileDraft(profile ?? blank));
  const [error, setError] = useState("");
  const setField = <K extends "gender" | "activityLevel" | "goal">(key: K, next: NutritionProfile[K]) => setValue((current) => ({ ...current, [key]: next }));
  const setNumber = (key: "age" | "heightCm" | "weightKg" | "calorieAdjustment", next: string) => setValue((current) => updateNutritionProfileDraft(current, key, next));
  const submit = (event: React.FormEvent) => { event.preventDefault(); const next = nutritionProfileFromDraft(value); if (next.error) return setError(next.error); setError(""); onSave(next); };
  return <form className="card nutrition-form" onSubmit={submit}><h2 style={{ marginTop: 0 }}>Set up your nutrition targets</h2><p className="muted" style={{ fontSize: 14 }}>Training is added separately after a completed workout.</p><div className="nutrition-grid"><label>Sex<select className="field" value={value.gender} onChange={(event) => setField("gender", event.target.value as NutritionProfile["gender"])}><option value="male">Male</option><option value="female">Female</option></select></label><label>Age<input className="field" type="number" inputMode="numeric" min="13" max="120" value={value.age} onChange={(event) => setNumber("age", event.target.value)} /></label><label>Height (cm)<input className="field" type="number" inputMode="decimal" min="100" value={value.heightCm} onChange={(event) => setNumber("heightCm", event.target.value)} /></label><label>Weight (kg)<input className="field" type="number" inputMode="decimal" min="25" step="0.1" value={value.weightKg} onChange={(event) => setNumber("weightKg", event.target.value)} /></label></div><label style={{ display: "block", marginTop: 14 }}>Non-training activity<select className="field" value={value.activityLevel} onChange={(event) => setField("activityLevel", event.target.value as NutritionProfile["activityLevel"])}><option value="sedentary">Mostly seated outside training</option><option value="light">Light daily movement / walking</option><option value="moderate">Active daily lifestyle</option><option value="active">Physical work / very active lifestyle</option></select></label><label style={{ display: "block", marginTop: 14 }}>Goal<select className="field" value={value.goal} onChange={(event) => setField("goal", event.target.value as NutritionProfile["goal"])}><option value="bulk">Bulk · +250 kcal surplus</option><option value="cut">Cut · -400 kcal deficit</option><option value="maintain">Maintain · maintenance calories</option></select></label><label style={{ display: "block", marginTop: 14 }}>Custom calorie adjustment (optional)<input className="field" type="number" inputMode="decimal" placeholder="Uses the goal default" value={value.calorieAdjustment} onChange={(event) => setNumber("calorieAdjustment", event.target.value)} /></label>{error && <p className="muted" role="alert">{error}</p>}<button className="button" style={{ marginTop: 18 }} type="submit">Save targets</button></form>;
}
