"use client";

import type { Exercise, WorkoutPlan } from "@/lib/types";

const id = () => `custom-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
export function PlanEditor({ plan, onChange }: { plan: WorkoutPlan; onChange: (plan: WorkoutPlan) => void }) {
  const updateExercise = (dayIndex: number, exerciseIndex: number, change: Partial<Exercise>) => onChange({ ...plan, days: plan.days.map((day, i) => i === dayIndex ? { ...day, exercises: day.exercises.map((exercise, j) => j === exerciseIndex ? { ...exercise, ...change } : exercise) } : day) });
  const removeExercise = (dayIndex: number, exerciseIndex: number) => onChange({ ...plan, days: plan.days.map((day, i) => i === dayIndex ? { ...day, exercises: day.exercises.filter((_, j) => j !== exerciseIndex) } : day) });
  const move = (dayIndex: number, exerciseIndex: number, direction: -1 | 1) => { const next = exerciseIndex + direction; if (next < 0 || next >= plan.days[dayIndex].exercises.length) return; const days = plan.days.map((day) => ({ ...day, exercises: [...day.exercises] })); [days[dayIndex].exercises[exerciseIndex], days[dayIndex].exercises[next]] = [days[dayIndex].exercises[next], days[dayIndex].exercises[exerciseIndex]]; onChange({ ...plan, days }); };
  return <div>{plan.days.map((day, dayIndex) => <section className="card plan-day" key={day.id}><input className="field" aria-label="Workout day name" value={day.name} onChange={(event) => onChange({ ...plan, days: plan.days.map((item, i) => i === dayIndex ? { ...item, name: event.target.value } : item) })} />{day.exercises.map((exercise, exerciseIndex) => <div className="plan-exercise" key={exercise.id}><input className="field" aria-label="Exercise name" value={exercise.name} onChange={(event) => updateExercise(dayIndex, exerciseIndex, { name: event.target.value })} /><input className="field" aria-label="Sets" type="number" min="1" value={exercise.targetSets} onChange={(event) => updateExercise(dayIndex, exerciseIndex, { targetSets: Math.max(1, Number(event.target.value) || 1) })} /><input className="field" aria-label="Target reps" value={exercise.targetReps} onChange={(event) => updateExercise(dayIndex, exerciseIndex, { targetReps: event.target.value })} /><input className="field" aria-label="Target weight" placeholder="weight" value={exercise.targetWeight ?? ""} onChange={(event) => updateExercise(dayIndex, exerciseIndex, { targetWeight: event.target.value || undefined })} /><span style={{ display: "flex", gap: 4 }}><button className="button secondary small" onClick={() => move(dayIndex, exerciseIndex, -1)} aria-label="Move exercise up">↑</button><button className="button secondary small" onClick={() => move(dayIndex, exerciseIndex, 1)} aria-label="Move exercise down">↓</button><button className="button secondary small" onClick={() => removeExercise(dayIndex, exerciseIndex)} aria-label="Delete exercise">×</button></span></div>)}<button className="button secondary small" style={{ marginTop: 14 }} onClick={() => onChange({ ...plan, days: plan.days.map((item, i) => i === dayIndex ? { ...item, exercises: [...item.exercises, { id: id(), name: "New exercise", targetSets: 3, targetReps: "10" }] } : item) })}>Add exercise</button></section>)}<button className="button secondary" onClick={() => onChange({ ...plan, days: [...plan.days, { id: id(), name: "New workout day", exercises: [] }] })}>Add workout day</button></div>;
}
