"use client";

import { useState } from "react";
import type { WorkoutBurnEstimate, WorkoutEffort, WorkoutSessionType } from "@/lib/types";

export function WorkoutBurnForm({ estimate, defaultType, onSave }: { estimate?: WorkoutBurnEstimate; defaultType: WorkoutSessionType; onSave: (duration: number, effort: WorkoutEffort, sessionType: WorkoutSessionType) => void }) {
  const savedSessionType = estimate?.sessionType ?? defaultType;
  const [duration, setDuration] = useState(estimate?.durationMinutes ?? 60); const [effort, setEffort] = useState<WorkoutEffort>(estimate?.effort ?? "moderate"); const [sessionType, setSessionType] = useState<WorkoutSessionType>(savedSessionType); const [error, setError] = useState("");
  const typeLabel = { upper: "upper-body", lower: "lower-body", full_body: "full-body", accessory: "light / accessory" }[savedSessionType];
  return <section className="card workout-burn"><strong>{estimate ? "Workout estimate" : "Workout complete"}</strong><p className="muted" style={{ margin: "6px 0 14px", fontSize: 13 }}>Add session type, duration, and effort for a calorie range estimate.</p><div className="nutrition-grid"><label>Session type<select className="field" value={sessionType} onChange={(event) => setSessionType(event.target.value as WorkoutSessionType)}><option value="upper">Upper body</option><option value="lower">Lower body</option><option value="full_body">Full body</option><option value="accessory">Light / accessory</option></select></label><label>Session duration (minutes)<input className="field" type="number" min="10" max="240" value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></label><label>Effort<select className="field" value={effort} onChange={(event) => setEffort(event.target.value as WorkoutEffort)}><option value="easy">Easy</option><option value="moderate">Moderate</option><option value="hard">Hard</option></select></label></div>{error && <p style={{ color: "#525252", fontSize: 13 }}>{error}</p>}<button className="button small" style={{ marginTop: 14 }} onClick={() => { if (!Number.isInteger(duration) || duration < 10 || duration > 240) { setError("Enter a whole number between 10 and 240 minutes."); return; } setError(""); onSave(duration, effort, sessionType); }}>{estimate ? "Update estimate" : "Save workout estimate"}</button>{estimate && <p style={{ margin: "13px 0 0", fontSize: 14 }}>Estimated workout burn: <strong>{estimate.lowCalories}–{estimate.highCalories} kcal</strong><br /><span className="muted" style={{ fontSize: 13 }}>Based on {estimate.durationMinutes} minutes, {estimate.effort} effort, {typeLabel}.</span></p>}<p className="muted" style={{ margin: "8px 0 0", fontSize: 12 }}>This range is estimated from session duration, effort, and session type—not a medical measurement.</p></section>;
}
