create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workout_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index one_active_plan_per_user on public.workout_plans(user_id) where is_active;
create table public.workout_days (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan_id uuid not null references public.workout_plans(id) on delete cascade, name text not null, position integer not null default 0, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.exercises (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_day_id uuid not null references public.workout_days(id) on delete cascade, name text not null, target_sets integer not null check(target_sets > 0), target_reps text not null, target_weight text, position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workout_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, session_date date not null, workout_day_id uuid not null references public.workout_days(id) on delete restrict, workout_day_name text not null, completed boolean not null default false, burn_estimate jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, session_date, workout_day_id));
create table public.completed_sets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_session_id uuid not null references public.workout_sessions(id) on delete cascade, exercise_id uuid references public.exercises(id) on delete set null, exercise_name text not null, set_index integer not null, done boolean not null default false, actual_reps text, actual_weight text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workout_session_id, exercise_id, set_index));
create table public.nutrition_profiles (user_id uuid primary key references auth.users(id) on delete cascade, gender text not null check(gender in ('male','female')), age integer not null check(age between 13 and 120), height_cm numeric not null check(height_cm > 0), weight_kg numeric not null check(weight_kg > 0), activity_level text not null check(activity_level in ('sedentary','light','moderate','active','very_active')), goal text not null check(goal in ('bulk','cut','maintain')), calorie_adjustment integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.nutrition_days (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, entry_date date not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, entry_date));
create table public.meal_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, nutrition_day_id uuid not null references public.nutrition_days(id) on delete cascade, name text not null, calories numeric not null check(calories >= 0), protein numeric not null default 0 check(protein >= 0), fat numeric not null default 0 check(fat >= 0), carbs numeric not null default 0 check(carbs >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.assert_parent_owner() returns trigger language plpgsql as $$ declare owner_id uuid; begin
  if tg_table_name = 'workout_days' then select user_id into owner_id from public.workout_plans where id = new.plan_id;
  elsif tg_table_name = 'exercises' then select user_id into owner_id from public.workout_days where id = new.workout_day_id;
  elsif tg_table_name = 'workout_sessions' then select user_id into owner_id from public.workout_days where id = new.workout_day_id;
  elsif tg_table_name = 'completed_sets' then select user_id into owner_id from public.workout_sessions where id = new.workout_session_id;
  elsif tg_table_name = 'meal_entries' then select user_id into owner_id from public.nutrition_days where id = new.nutrition_day_id;
  end if; if owner_id is distinct from new.user_id then raise exception 'Parent record does not belong to current user'; end if; return new; end; $$;

do $$ declare t text; begin foreach t in array array['profiles','workout_plans','workout_days','exercises','workout_sessions','completed_sets','nutrition_profiles','nutrition_days','meal_entries'] loop execute format('create trigger %I before update on public.%I for each row execute procedure public.set_updated_at()', 'set_updated_at_' || t, t); execute format('alter table public.%I enable row level security', t); end loop; end $$;
create trigger parent_owner_days before insert or update on public.workout_days for each row execute procedure public.assert_parent_owner();
create trigger parent_owner_exercises before insert or update on public.exercises for each row execute procedure public.assert_parent_owner();
create trigger parent_owner_sessions before insert or update on public.workout_sessions for each row execute procedure public.assert_parent_owner();
create trigger parent_owner_sets before insert or update on public.completed_sets for each row execute procedure public.assert_parent_owner();
create trigger parent_owner_meals before insert or update on public.meal_entries for each row execute procedure public.assert_parent_owner();

do $$ declare t text; begin foreach t in array array['workout_plans','workout_days','exercises','workout_sessions','completed_sets','nutrition_profiles','nutrition_days','meal_entries'] loop execute format('create policy "own_select_%s" on public.%I for select using (auth.uid() = user_id)', t,t); execute format('create policy "own_insert_%s" on public.%I for insert with check (auth.uid() = user_id)',t,t); execute format('create policy "own_update_%s" on public.%I for update using (auth.uid() = user_id) with check (auth.uid() = user_id)',t,t); execute format('create policy "own_delete_%s" on public.%I for delete using (auth.uid() = user_id)',t,t); end loop; end $$;
create policy "own_select_profiles" on public.profiles for select using(auth.uid()=id); create policy "own_update_profiles" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
